# Generated by Django 5.0.4 on 2024-05-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zxl', '0004_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='mobile',
            field=models.CharField(max_length=11, verbose_name='手机号'),
        ),
    ]
