# Generated by Django 5.0.4 on 2024-05-29 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zxl', '0006_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='任务名称')),
                ('content', models.CharField(max_length=100, verbose_name='任务内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('level', models.SmallIntegerField(choices=[(1, '紧急'), (2, '重要'), (3, '一般')], verbose_name='优先级')),
                ('status', models.SmallIntegerField(choices=[(1, '未完成'), (2, '已完成')], verbose_name='状态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zxl.admin', verbose_name='负责人')),
            ],
        ),
    ]
