# Generated by Django 5.0.4 on 2024-05-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zxl', '0008_alter_task_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.TextField(verbose_name='任务内容'),
        ),
    ]
