# Generated by Django 5.0.4 on 2024-06-01 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zxl', '0009_alter_task_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.TextField(max_length=100, verbose_name='任务内容'),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_time',
            field=models.DateTimeField(verbose_name='创建时间'),
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(max_length=32, verbose_name='订单号')),
                ('title', models.CharField(max_length=100, verbose_name='商品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('status', models.SmallIntegerField(choices=[(1, '已支付'), (2, '未支付')], verbose_name='订单状态')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zxl.admin', verbose_name='用户')),
            ],
        ),
    ]
