# Generated by Django 5.0.4 on 2024-06-01 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zxl', '0010_alter_task_content_alter_task_create_time_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zxl.admin', verbose_name='管理员'),
        ),
    ]
