# Generated by Django 5.0.4 on 2024-06-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zxl', '0011_alter_order_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='boost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('img', models.ImageField(max_length=128, upload_to='', verbose_name='头像')),
            ],
        ),
    ]
