# Generated by Django 5.0.4 on 2024-06-12 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zxl', '0012_boost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='boost',
            new_name='boos',
        ),
    ]
