# Generated by Django 5.0.4 on 2024-06-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zxl', '0014_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boos',
            name='name',
            field=models.CharField(max_length=100, verbose_name='城市'),
        ),
    ]
