# Generated by Django 5.0.4 on 2024-10-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zxl', '0016_alter_city_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='城市')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('high', models.FloatField(verbose_name='身高')),
                ('weight', models.FloatField(verbose_name='体重')),
            ],
        ),
    ]
