# Generated by Django 5.0.4 on 2024-10-17 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zxl', '0018_alter_test_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='name',
            new_name='username',
        ),
    ]
